<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Library</OutputType>

    <Version>1.0.0</Version>
    <AssemblyTitle>Debugger</AssemblyTitle>
    <Authors>Gerard</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fmpostor.Api\Fmpostor.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
