<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <Version>1.0.0</Version>
    <AssemblyTitle>Example</AssemblyTitle>
    <Authors>AeonLucid</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fmpostor.Api\Fmpostor.Api.csproj" />
  </ItemGroup>

</Project>
